spring:
  application:
    name: Products Gerence
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2